Repository DeveloperAcademy-POSTECH/2024-NC2-M1-NFC, pull requests merged in 2024-06, with the labels that each got.

#4 Feature/#3
  Pikacho/Pikacho.xcodeproj/project.pbxproj
  Pikacho/Pikacho/Model/PCBooking.swift
  Pikacho/Pikacho/Model/PCColorList.swift
  Pikacho/Pikacho/Util/ColorWithHex.swift
  Pikacho/Pikacho/View/ContentView.swift
Labels: feature

#7 [#5] 메인 뷰 그리기
  Pikacho/Pikacho.xcodeproj/project.pbxproj
  Pikacho/Pikacho/Model/PCColorList.swift
  Pikacho/Pikacho/Util/NFCFeature.swift
  Pikacho/Pikacho/View/ContentView.swift
  Pikacho/Pikacho/View/NFCTagScanView.swift
Labels: design

#14 [#8] NFC 태그 기능 작업
  Pikacho/Pikacho/Model/PCColorList.swift
  Pikacho/Pikacho/PikachoApp.swift
  Pikacho/Pikacho/Util/NFCFeature.swift
  Pikacho/Pikacho/View/CheckView.swift
  Pikacho/Pikacho/View/ContentView.swift
  Pikacho/Pikacho/View/NFCTagScanView.swift
Labels: feature

#18 [#13] 수정삭제하기 뷰 그리기
  Pikacho/Pikacho.xcodeproj/project.pbxproj
  Pikacho/Pikacho/Model/PCBooking.swift
  Pikacho/Pikacho/PikachoApp.swift
  Pikacho/Pikacho/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  Pikacho/Pikacho/Resource/Assets.xcassets/AppIcon.appiconset/Meet-ing_icon_xc.png
  Pikacho/Pikacho/View/BookingView.swift
  Pikacho/Pikacho/View/CheckView.swift
  Pikacho/Pikacho/View/DetailView.swift
  Pikacho/Pikacho/View/UpdateView.swift
Labels: design

#19 [#00] 태그 오류 최종 수정
  Pikacho/Pikacho.xcodeproj/project.pbxproj
  Pikacho/Pikacho/Info.plist
  Pikacho/Pikacho/Pikacho.entitlements
  Pikacho/Pikacho/Util/NFCFeature.swift
  Pikacho/Pikacho/View/NFCTagScanView.swift
Labels: fix
